[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = [
  'cd pump-sdk && npm install && npm run build',
  'npm install'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'