[phases.setup]
cmds = [
    "cp -r ../pump-sdk ./pump-sdk",
    "sed -i 's/\"file:..\/pump-sdk\"/\"file:.\\/pump-sdk\"/g' package.json"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]